### ISSUE TITLE
Lista av buggar i fabian2

### ISSUE THREAD

**Issue by iAmSamFlo** [iAmSamFlo/projinda23#12]
Just nu ligger den bästa versionen i fabian2. Detta ty att main spåra och chatgpt hjälpte inte att resolva knas så vi fick back tracka lite för att korrigera koden. Under så finns lite problem med den nuvarande koden där:

1. Färgen genereras bara när blocked har gått till botten.
2. blocked är inte rätt när de rotatar. 
3. Kan inte hålla ner K_DOWN måste spamma men venne om d går att fixa.

**Comment by iAmSamFlo** [comment]
Nummer 3 är åtgärdat

**Comment by iAmSamFlo** [comment]
blocked := blocken

**Comment by fabianoest** [comment]
nummer 2 åtgärdat

**Comment by fabianoest** [comment]
nummer 1 åtgärdat
