### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by tipptapp** [iAmSamFlo/projinda23#18]
1. Projektbeskrivning: skulle kanske kunna ha lite mer detaljerat om hur spelet mer ingående ska fungera och vad som ska finnas med. Vad går spelet ut på? Hur vinner man?
2. Dokumentation: dokumentationen i koden gör att man förstår vad varje metods uppgift är. Skulle kunna lägga till lite mer om hur de fungerar, men förstår att man kontinuerligt ändrar koden så känns mer rimligt att skriva mer utförlig dokumentation i slutet. 
3. Milestones: skulle kunna skriva lite mer om varje milestone, vad som ska göras inom vardera. Typ vilka klasser och metoder som är tänkta att finnas med. 
4. Issues and labels: issues ser bra ut. Står vad som ska göras, och det finns follow-ups i en av dem, där ni skrivit att det åtgärdats osv. 
5. Branching: jag vet inte om man ska göra detta, men ni kanske skulle kunna namnge era branches så att man vet från namnet vad som pågår i denna branch. Annars tycker jag det ser bra ut där man ser att ni arbetat i olika branches och sedan mergat till main-branchen. 
6. Se ovan
Commitsen har också bra beskrivningar, men ni skulle kanske kunna skriva mer om vad som ska göras när ni commitat, och mindre vad som gjorts.

**Comment by fabianoest** [comment]
README.md uppdaterad, jobbar på dokumentation i fabianos2

**Comment by fabianoest** [comment]
Dokumentation uppdaterad i fabianos2

**Comment by fabianoest** [comment]
Milestones uppdaterade

**Comment by fabianoest** [comment]
Review klar
