### ISSUE TITLE
Spel saknas

### ISSUE THREAD

**Issue by AdamNjeg** [iAmSamFlo/projinda23#3]
Det finns ju förfan inget spel här, jag trodde ni gick på data?

**Comment by iAmSamFlo** [comment]
Vi jobbar på macOS, du som e beta windows user måste såklart ta bort system32 innan du kan köra spel.
Här har do bra [tutorial](https://www.youtube.com/watch?v=dpjoUu_24ys) noob.

**Comment by iAmSamFlo** [comment]
Spel finns nu lillpojk, tyvärr jättebuggit men ducka de detaljerna!!!111!
